export const SHOW_ALL_CLIENTS = 'SHOW_ALL_CLIENTS'
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS'


export const SHOW_ALL_CLIENTS_SAGA = 'SHOW_ALL_CLIENTS_SAGA'
export const SEARCH_CLIENTS_SAGA = 'SEARCH_CLIENTS_SAGA'
