export const SHOW_ORDER = 'SHOW_ORDER'
export const ADD_ORDER = 'ADD_ORDER'
export const EDIT_ORDER = 'EDIT_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'
export const ADD_COMMENT_ORDER = 'ADD_COMMENT_ORDER'

export const SHOW_ORDER_SAGA = 'SHOW_ORDER_SAGA'
export const ADD_ORDER_SAGA = 'ADD_ORDER_SAGA'
export const EDIT_ORDER_SAGA = 'EDIT_ORDER_SAGA'
export const DELETE_ORDER_SAGA = 'DELETE_ORDER_SAGA'
export const ADD_COMMENT_ORDER_SAGA = 'ADD_COMMENT_ORDER_SAGA'

export const FIND_CLIENTS_FOR_NEW_ORDER = 'FIND_CLIENTS_FOR_NEW_ORDER'
export const FIND_CLIENTS_FOR_NEW_ORDER_SAGA = 'FIND_CLIENTS_FOR_NEW_ORDER_SAGA'