export const SHOW_ALL_ORDERS = 'SHOW_ALL_ORDERS'
export const SEARCH_ORDERS = 'SEARCH_ORDERS'

export const SHOW_ALL_ORDERS_SAGA = 'SHOW_ALL_ORDERS_SAGA'
export const SEARCH_ORDERS_SAGA = 'SEARCH_ORDERS_SAGA'
