export const SHOW_ALL_USERS = 'SHOW_ALL_USERS'
export const SHOW_ALL_USERS_SAGA = 'SHOW_ALL_USERS_SAGA'


export const INIT_USER = 'INIT_USER'
export const INIT_USER_SAGA = 'INIT_USER_SAGA'


export const DELETE_MAIL = 'DELETE_MAIL'
export const DELETE_MAIL_SAGA = 'DELETE_MAIL_SAGA'